name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: deps
      run: sudo apt-get update && sudo apt-get install -y libsdl3-dev

    - name: build fr
      run: make
