name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: install SDL3 dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake build-essential libx11-dev libxext-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxfixes-dev libxss-dev libxtst-dev libwayland-dev libegl-dev

    - name: build SDL3 from source
      run: |
        cmake -S external/SDL -B external/SDL/build
        cmake --build external/SDL/build
        sudo cmake --install external/SDL/build

    - name: build from source
      run: make
